### ISSUE TITLE
Shematic BlackPill STM32F411 to PCM5102 Module

### ISSUE THREAD

**Issue by kloker2** [har-in-air/STM32F411_USB_AUDIO_DAC#1]
**BlackPill-F411         PCM5102 Module**
+5v                         VCC
NC                          3.3V
GND              |-       GND
GND              |-        FLT
GND              |-       DMP
GND              |-       SCL	I2Sx_MCK_PIN  (Master Clock)
B13 I2Sx_SCK_PIN  BCK	Тактовый сигнал битовой синхронизации (CLK)Bit clock or serial clock
B15 I2Sx_SD_PIN    DIN	Сигнал данных, который может передавать или принимать 2 разделённых по времени канала. (SD)
B12 I2Sx_WS_PIN   LCK	Тактовый сигнал фреймовой (по словам) синхронизации (WS word select)
GND              |-      FMT		
B8  MUTE_PIN       XMT	Mute Software
_________________________________________
A6	I2Sx_MCK_PIN	NC (Master Clock)
_________________________________________
**Board Leds**
B3    LED_RED          // 96000
B6    LED_GREEN     // 48000
B9    LED_BLUE        // 44100

**Comment by har-in-air** [comment]
Have updated the pinout in the README, thanks
