### ISSUE TITLE
Using other DACs

### ISSUE THREAD

**Issue by radiomanoff** [har-in-air/STM32F411_USB_AUDIO_DAC#10]
Thanks for the project. STM32F401CCU6 + PCM5102 bundle worked without problems under Linux Mint
Using other DACs with MCLK (Master Clock) support?
Is the pin turned on - MCLK (Master Clock)?

**Comment by har-in-air** [comment]
Look at the makefile, enable USE_MCLK_OUT
```
# C definesC_DEFS =  \-DUSE_HAL_DRIVER \-DUSE_FULL_ASSERT \-D$(CPU_DEF) \-DDEBUG_FEEDBACK_ENDPOINT # -DUSE_MCLK_OUT 
```

**Comment by radiomanoff** [comment]
Thank you. But unfortunately STM32F401CCU6 does not support master clock
[https://radiomanoff.at.ua/_ph/1/383999272.png](url)

**Comment by har-in-air** [comment]
Thanks, fixed conditional compilation for MCLK output and corrected the readme
