### ISSUE TITLE
An little contribution to make easy the implementation of your code

### ISSUE THREAD

**Issue by FAUSTINOCRUZELIS** [har-in-air/STM32F411_USB_AUDIO_DAC#13]
[Drive link to Gerber file of My prototype PCB design](https://drive.google.com/file/d/16NNwvrwQJbw5402ePAMmbVkY0LZwi2i0/view?usp=drivesdk)

**Comment by DeflateAwning** [comment]
@FAUSTINOCRUZELIS, it would be awesome if you could put this in a GitHub repo, ideally with the source design files (from whatever software you used to make it), and the Gerber in a "Release". 

I'm considering doing something similar, and would love to take a look at what you made! 

Also, the Google Drive link is now broken.
