### ISSUE TITLE
Can you make it work with alc883(TDM codec)?

### ISSUE THREAD

**Issue by Raduq91** [har-in-air/STM32F411_USB_AUDIO_DAC#15]
![t1](https://user-images.githubusercontent.com/31180871/226113435-b8197201-807b-43ba-a731-ab285b1adbb3.png)
![t2](https://user-images.githubusercontent.com/31180871/226113450-1f80ef78-0c82-4465-847e-81ae74262369.png)
datasheet:
[alc883.pdf](https://github.com/har-in-air/STM32F411_USB_AUDIO_DAC/files/11008833/alc883.pdf)

**Comment by har-in-air** [comment]
This is not an issue, closed
