### ISSUE TITLE
is there an easy way to add an ADC

### ISSUE THREAD

**Issue by OwnGamesGamer** [har-in-air/STM32F411_USB_AUDIO_DAC#16]
I would want to have an ADC and a DAC connected to this to recors and play audio on my pc. would that be possible with this or with small modifications?

**Comment by har-in-air** [comment]
You can search for this in the stm32 official code repository 

Sent from Yahoo Mail on Android 
 
  On Mon, 24 Apr 2023 at 16:40, ***@***.***> wrote:   


I would want to have an ADC and a DAC connected to this to recors and play audio on my pc. would that be possible with this or with small modifications?

**Comment by DeflateAwning** [comment]
It looks like at least one fork has gotten an ADC working:
* https://github.com/mcginty/wombo_old

Not sure how well it works, but just wanted to share that I found it.
