### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by smagtech** [har-in-air/STM32F411_USB_AUDIO_DAC#18]
I'm getting this error. I'm new with  stm32cubeide. and their is no file call .ioc in your STM32F411_USB_AUDIO_DAC-main file. Please help. 
if step by step guide will be more helpful. 

 STM32CubeIDE
Version: 1.13.2

error is....

17:56:38 **** Incremental Build of configuration Default for project ok4 ****
make all 
Cannot run program "make": Launching failed

Error: Program "make" not found in PATH
PATH=[C:/ST/STM32CubeIDE_1.13.2/STM32CubeIDE//plugins/com.st.stm32cube.ide.jre.win64_3.0.0.202305091045/jre/bin/server;C:/ST/STM32CubeIDE_1.13.2/STM32CubeIDE//plugins/com.st.stm32cube.ide.jre.win64_3.0.0.202305091045/jre/bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Cypress\EZ-USB FX3 SDK\1.3\util\elf2img\;C:\Program Files\Git\cmd;C:\Users\G_Sudhir\AppData\Local\Microsoft\WindowsApps;;C:\Users\G_Sudhir\AppData\Local\Programs\Microsoft VS Code\bin;C:\ST\STM32CubeIDE_1.13.2\STM32CubeIDE]

17:56:38 Build Failed. 1 errors, 0 warnings. (took 70ms)

**Comment by har-in-air** [comment]
I'm sorry that you mistook a public Github code repository for an instructables project.
Try using google with the search "stm32cubeide make not found in path".

Hint : this is a makefile project, that is clearly specified in the introduction. You don't even need an IDE. You just need the toolchain and path correctly set for all the binaries. You can build and flash directly from the command line. If you want to use Stm32CubeIDE, google "Stm32CubeIDE makefile project".  I face multiple similar issues in every project, but I look for solutions on Google  before behaving like an entitled spoon-fed infant.

You could have simply done this,  and then posted an issue where you mentioned that you faced this problem and one sentence  where you explained what was required with any links to webpages etc.  That would have been a productive contribution to the open source community, even if I closed the issue without responding.

As an example of being productive, someone got irritated that I didn't include a schematic. He sent me an email and included a text table with the pin connections. I rewrote that with more information and included it in the README.

**Comment by smagtech** [comment]
finely made it run working fine. 

thank you for advise .
