### ISSUE TITLE
I need your help please

### ISSUE THREAD

**Issue by cavl3108** [har-in-air/STM32F411_USB_AUDIO_DAC#23]
hola, que posibilidad hay de que me pueda ayudar a montar o desarrollar un codigo en base a este, asi sea necesario pagarle, es que necesito en base a la tarjeta black pill y la pcm5102, con el protocolo de audio usb crear una especie de crosover y ecualizador grafico digital donde haga uso del nucleo DSP integrado en la tarjeta y el control de las ganancias de bandas se realice por medio de una interfaz grafica ya sea digital por aplicacion en android o una interfaz analoga, porfavor necesito su ayuda.
Hello, what is the possibility that you can help me set up or develop a code based on this, even if it is necessary to pay you, I need, based on the black pill card and the pcm5102, with the USB audio protocol to create a kind of crossover and digital graphic equalizer where it makes use of the DSP core integrated into the card and the control of the band gains is carried out through a graphic interface, either digital through an Android application or an analog interface, please I need your help.

**Comment by har-in-air** [comment]
Sorry, won't be able to help you with this. You should post on the facebook stm32 groups.

Sent from Yahoo Mail on Android 
 
  On Tue, 30 Jan 2024 at 8:21 am, ***@***.***> wrote:   


hola, que posibilidad hay de que me pueda ayudar a montar o desarrollar un codigo en base a este, asi sea necesario pagarle, es que necesito en base a la tarjeta black pill y la pcm5102, con el protocolo de audio usb crear una especie de crosover y ecualizador grafico digital donde haga uso del nucleo DSP integrado en la tarjeta y el control de las ganancias de bandas se realice por medio de una interfaz grafica ya sea digital por aplicacion en android o una interfaz analoga, porfavor necesito su ayuda.
Hello, what is the possibility that you can help me set up or develop a code based on this, even if it is necessary to pay you, I need, based on the black pill card and the pcm5102, with the USB audio protocol to create a kind of crossover and digital graphic equalizer where it makes use of the DSP core integrated into the card and the control of the band gains is carried out through a graphic interface, either digital through an Android application or an analog interface, please I need your help.
