### ISSUE TITLE
Are you interested in adding the files to make your project work in STM32CubeIDE on Windows?

### ISSUE THREAD

**Issue by robcazzaro** [har-in-air/STM32F411_USB_AUDIO_DAC#7]
I ported your project to STM32CubeIDE on Windows, and if you are interested, I have included here all the files (for STM32F411, if you also want for the 401 I will need to tweak a couple of things)

[STM32F411UAD.zip](https://github.com/har-in-air/STM32F411_USB_AUDIO_DAC/files/6490113/STM32F411UAD.zip)

**Comment by har-in-air** [comment]
Thanks
